name: Generate Release Notes

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v2.1.0

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Release Notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
